### ISSUE TITLE
To write ss_history in UTC and show them in local time

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#22]
I found time in `ss_history` is not recorded in proper Unix timestamp.
Though it can be easily figured out, but I'm feeling headache to make it...
and existed SQL entries need to correct.

BTW entry id=13 (Snow wings) entries shall be EVENT, but not SR. (Due to the assign issue)

**Comment by summertriangle-dev** [comment]
I'll redo them when I find a good changelog source.

Note that the ss_history timestamp depends on what time storage.game.starlight-stage.jp says it is, which usually isn't exactly the update time.

Also, the timestamps are completely wrong from f47457b9f09380c6d162ea7dd185a63cc9669dc1 to f917e130fcde8b2d150201daae878e26ff61e69a because I was using the old db's mtime.

**Comment by summertriangle-dev** [comment]
I've redone the history entirely, it should be more accurate now.

To generate the new table, run `python3 toolchain/update_rich_history.py _data/transient/____.mdb` with the environment set (or just let auto-update do it for you)

Dates are currently still in UTC, I plan to get some converting JS done soon.

**Comment by CaiMiao** [comment]
My history is now disappeared.
As I'm fighting for SSS , could you help me check what happens?

发自我的 iPhone

**Comment by CaiMiao** [comment]
ok  it works now lol. I deleted current mdb and re-update it, then works.

**Comment by CaiMiao** [comment]
放課後タイムガシャ shows double in histrory page.

**Comment by summertriangle-dev** [comment]
There was a cinfes in the middle of it.

**Comment by CaiMiao** [comment]
closing due to low priority
